"""
make_tables_numbers.py -- single source of truth for every number quoted in the manuscript.

Reads only committed CSV/JSON artifacts under reports/ and writes
  paper/generated/numbers.tex     \\newcommand macros used in the text (one macro per quoted number)
  paper/generated/claims.csv      ledger: macro, value, source file, how it was computed
  paper/generated/tab_*.tex       every results table in the paper
verify_submission.py re-runs this script into a temporary directory and fails if any output differs, so the
PDF cannot drift from the artifacts.

    python src/synthesis/make_tables_numbers.py [--out DIR]
"""
import argparse
import json
import os

import numpy as np
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
R = lambda *p: os.path.join(ROOT, 'reports', *p)  # noqa: E731


class Ledger:
    def __init__(self):
        self.rows = []

    def add(self, name, value, src, how, fmt='{:.3f}'):
        txt = fmt.format(value) if not isinstance(value, str) else value
        self.rows.append(dict(macro=name, value=txt, source=src, how=how))
        return txt

    def tex(self):
        out = ['% AUTO-GENERATED by src/synthesis/make_tables_numbers.py -- do not edit by hand']
        for r in self.rows:
            out.append('\\newcommand{\\%s}{%s}' % (r['macro'], r['value']))
        return '\n'.join(out) + '\n'


def pct(x, d=0):
    return ('{:.%df}' % d).format(100 * x)


def f(x, d=2):
    return ('{:.%df}' % d).format(x)


def main(outdir):
    os.makedirs(outdir, exist_ok=True)
    L = Ledger()
    tabs = {}

    # ---------------- factorial (synthetic label-mixing proxy) ----------------------------------------------
    corr = pd.read_csv(R('factorial_reliability_correlations.csv')).iloc[0]
    src = 'reports/factorial_reliability_correlations.csv'
    for k, m in [('Spearman_Run_Difficulty', 'FacRhoD'), ('Spearman_Run_ProxyError', 'FacRhoEps'),
                 ('Spearman_Run_InvLambda', 'FacRhoLam'), ('Spearman_Run_Additive', 'FacRhoAdd'),
                 ('Spearman_Cell_Difficulty', 'FacRhoDCell')]:
        L.add(m, corr[k], src, k)
    rc = pd.read_csv(R('factorial_risk_coverage.csv'))
    row40 = rc.iloc[(rc.iloc[:, 0] - 0.4).abs().argmin()]
    full = rc.iloc[(rc.iloc[:, 0] - 1.0).abs().argmin()]
    L.add('FacRetainErr', row40.iloc[2], 'reports/factorial_risk_coverage.csv', 'mean error at 40% retention', '{:.2f}')
    L.add('FacFullErr', full.iloc[2], 'reports/factorial_risk_coverage.csv', 'mean error at 100% retention', '{:.2f}')
    raw = pd.read_csv(R('factorial_reliability_raw.csv'))
    L.add('FacNRuns', len(raw), 'reports/factorial_reliability_raw.csv', 'rows', '{:,}')
    cf = json.load(open(R('synthesis', 'closed_form_factorial_summary.json')))
    s = 'reports/synthesis/closed_form_factorial_summary.json'
    L.add('CFRatioMed', cf['ratio_median'], s, 'median obs/pop over eps>0 cells')
    L.add('CFRatioLo', cf['ratio_q25'], s, 'q25'); L.add('CFRatioHi', cf['ratio_q75'], s, 'q75')
    L.add('CFRatioMin', cf['ratio_min'], s, 'min', '{:.2f}'); L.add('CFRatioMax', cf['ratio_max'], s, 'max', '{:.2f}')
    L.add('CFNCells', cf['n_cells_compared'], s, 'cells', '{:d}')
    L.add('CFLamInfl', cf['lambda_inflation_smallest_sigma'], s, 'lambda(eps=.4)/lambda(eps=0) at sigma1=.08', '{:.0f}')
    L.add('CFLamLo', cf['lambda_smallest_sigma_eps0'], s, 'lambda at eps=0', '{:.4f}')
    L.add('CFLamHi', cf['lambda_smallest_sigma_epsmax'], s, 'lambda at eps=.4', '{:.3f}')
    L.add('CFErrPeak', cf['err_smallest_sigma_peak'], s, 'peak median error at sigma1=.08', '{:.0f}')
    L.add('CFErrEnd', cf['err_smallest_sigma_epsmax'], s, 'median error at eps=.4, sigma1=.08', '{:.0f}')
    L.add('CFRhoProxy', cf['spearman_cell_D_proxy'], s, 'cell Spearman eps/lambda_proxy')
    L.add('CFRhoDesign', cf['spearman_cell_D_design'], s, 'cell Spearman eps/sigma1^2')
    L.add('CFNHump', cf['n_sigma_with_interior_hump'], s, 'sigma levels with interior maximum', '{:d}')
    pk = {p['sigma1']: p for p in cf['peaks']}
    for sg, m in [(0.08, 'A'), (0.15, 'B'), (0.3, 'C')]:
        L.add('CFPeak' + m, pk[sg]['eps_peak_observed'], s, f'observed argmax eps at sigma1={sg}', '{:.2f}')
    cells = pd.read_csv(R('synthesis', 'closed_form_factorial_cells.csv'))
    mat = cells[cells.eps > 0].pivot(index='sigma1', columns='eps', values='ratio_obs_over_pop')
    lines = ['\\begin{tabular}{l' + 'c' * mat.shape[1] + '}', '\\toprule',
             '$\\sigma_1\\backslash\\varepsilon_\\gamma$ & ' + ' & '.join(f'{c:g}' for c in mat.columns) + ' \\\\',
             '\\midrule']
    for sg, r in mat.iterrows():
        lines.append(f'{sg:g} & ' + ' & '.join(f'{v:.3f}' for v in r.values) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_closed_form'] = '\n'.join(lines)

    # ---------------- learned posteriors (coupled OR-DML) -----------------------------------------------------
    sc = pd.read_csv(R('synthesis', 'learned_posterior_coupled_scores.csv')).set_index('score')
    meta = json.load(open(R('synthesis', 'learned_posterior_coupled_meta.json')))
    s = 'reports/synthesis/learned_posterior_coupled_scores.csv'
    L.add('LPRhoD', sc.loc['eps_over_lam_proxy', 'spearman_run_all'], s, 'eps/lambda_proxy, run level')
    L.add('LPRhoDOracle', sc.loc['eps_over_lam_oracle', 'spearman_run_all'], s, 'eps/lambda_oracle')
    L.add('LPRhoScaled', sc.loc['scaled_eps_shift_over_lam_proxy', 'spearman_run_all'], s, 'eps*dm*dy/lambda_proxy')
    L.add('LPRhoScaledCell', sc.loc['scaled_eps_shift_over_lam_proxy', 'spearman_cell_all'], s, 'cell level')
    L.add('LPRhoScaledEnt', sc.loc['scaled_entropy_shift_over_lam_proxy', 'spearman_run_all'], s, 'observable scaled')
    L.add('LPRhoEnt', sc.loc['entropy_over_lam_proxy', 'spearman_run_all'], s, 'entropy/lambda_proxy')
    s = 'reports/synthesis/learned_posterior_coupled_meta.json'
    L.add('LPNRuns', meta['n_runs'], s, 'runs', '{:d}'); L.add('LPNCells', meta['n_cells'], s, 'cells', '{:d}')
    L.add('LPFracInfl', 100 * meta['frac_runs_lam_proxy_gt_oracle'], s, '% runs lambda_proxy>lambda_oracle', '{:.0f}')
    L.add('LPInflMed', meta['median_lam_inflation'], s, 'median lambda_proxy/lambda_oracle', '{:.1f}')
    L.add('LPInflQn', meta['lam_inflation_q90'], s, 'q90 ratio', '{:.0f}')
    L.add('LPHardBetter', 100 * meta['frac_cells_hard_better'], s, '% cells hard FE better', '{:.0f}')
    L.add('LPErrRatio', meta['median_err_ratio_coupled_over_hard'], s, 'median coupled/hard error', '{:.2f}')
    L.add('LPPABetter', 100 * meta['frac_cells_pa_better_than_hard'], s, '% cells posterior-adjusted OR-DML beats hard FE', '{:.0f}')
    L.add('LPPARunsBetter', 100 * meta['frac_runs_pa_better_than_hard'], s, '% runs posterior-adjusted beats hard FE', '{:.0f}')
    L.add('LPPARatio', meta['median_err_ratio_pa_over_hard'], s, 'median cell error ratio posterior-adjusted/hard', '{:.2f}')
    L.add('LPPAvsW', meta['median_err_ratio_pa_over_weighted'], s, 'median cell error ratio posterior-adjusted/weighted', '{:.2f}')
    names = [('eps_only', '$\\varepsilon_\\gamma$ (posterior error)', 'FacRhoEps'),
             ('inv_lam_proxy', '$1/\\lambda_{\\min}(\\hat J)$', 'FacRhoLam'),
             ('eps_over_lam_proxy', '$\\varepsilon_\\gamma/\\lambda_{\\min}(\\hat J)$', 'FacRhoD'),
             ('entropy_over_lam_proxy', '$\\bar H/\\lambda_{\\min}(\\hat J)$ (observable)', None),
             ('eps_over_lam_oracle', '$\\varepsilon_\\gamma/\\lambda_{\\min}(J^\\star)$ (oracle geometry)', None),
             ('scaled_entropy_shift_over_lam_proxy', '$\\bar H\\,|\\hat\\Delta_T\\hat\\Delta_Y|/\\lambda_{\\min}(\\hat J)$ (observable)', None),
             ('scaled_eps_shift_over_lam_proxy', '$\\varepsilon_\\gamma|\\hat\\Delta_T\\hat\\Delta_Y|/\\lambda_{\\min}(\\hat J)$', None)]
    lines = ['\\begin{tabular}{lcccc}', '\\toprule',
             '& \\multicolumn{1}{c}{synthetic proxy} & \\multicolumn{3}{c}{learned HMM posteriors} \\\\',
             '\\cmidrule(lr){2-2}\\cmidrule(lr){3-5}',
             'Failure score & runs & runs & within $\\Delta_T$ & cells \\\\', '\\midrule']
    fac = {'FacRhoEps': corr['Spearman_Run_ProxyError'], 'FacRhoLam': corr['Spearman_Run_InvLambda'],
           'FacRhoD': corr['Spearman_Run_Difficulty']}
    for key, lab, fk in names:
        r = sc.loc[key]
        fv = f(fac[fk], 3) if fk else '--'
        lines.append(f'{lab} & {fv} & {r.spearman_run_all:.3f} & {r.spearman_run_within_dm:.3f} & {r.spearman_cell_all:.3f} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_scores'] = '\n'.join(lines)

    # ---------------- observability frontier + hourly semi-synthetic: main comparison table -----------------
    bm = pd.read_csv(R('or_dml_benchmark_summary.csv'))          # legacy 11-method frontier (appendix only)
    fd = pd.read_csv(R('synthesis', 'frontier_designs_summary.csv'))
    ss = pd.read_csv(R('synthesis', 'semisynthetic_hourly_summary.csv'))
    cal = pd.read_csv(R('synthesis', 'semisynthetic_hourly_calibration.csv'))
    ROWS = [('Oracle-state', 'Oracle-state', 'Oracle-state regime DML'),
            ('Standard DML', 'Standard DML', 'Standard DML (random folds)'),
            ('Block DML', 'Block DML', 'Block DML (purged folds)'),
            ('DML + $Z$ controls', 'DML + Z controls', 'DML + Z controls'),
            ('Posterior-feature DML', 'Posterior-feature DML', 'Posterior-feature DML'),
            ('Hard regime FE', 'Hard regime FE', 'Hard regime FE DML'),
            ('OR-DML, weighted nuisances', 'OR-DML, weighted nuisances', 'Spectral OR-DML (soft, coupled)'),
            ('\\textbf{OR-DML} (posterior-adjusted)', 'OR-DML', 'OR-DML (posterior-adjusted)')]
    COUPLED = [r for r in ROWS if r[1] in ('Hard regime FE', 'OR-DML, weighted nuisances', 'OR-DML')]
    cities = ['Delhi', 'Mumbai', 'Bengaluru', 'Kolkata']
    dzs = [1.0, 2.0, 4.0]
    fdm = fd[fd.p00 == 0.88]
    gf = lambda d, m, col='mean_abs_bias', p00=0.88: fd[(fd.dz == d) & (fd.p00 == p00) & (fd.method == m)][col].iloc[0]  # noqa: E731
    gs = lambda c, m, col='mean_abs_bias': ss[(ss.city == c) & (ss.method == m)][col].iloc[0]  # noqa: E731

    def block(rows, fcol, scol):
        best = {('f', d): min(gf(d, r[1], fcol) for r in rows if r[1] != 'Oracle-state') for d in dzs}
        best.update({('s', c): min(gs(c, r[2], scol) for r in rows if r[1] != 'Oracle-state') for c in cities})
        out = []
        for lab, fm, sm in rows:
            cells_txt = []
            for d in dzs:
                v = gf(d, fm, fcol)
                txt = f(v, 2) if v < 10 else f(v, 1)
                cells_txt.append('\\textbf{%s}' % txt if fm != 'Oracle-state' and v - best[('f', d)] < 5e-4 else txt)
            for c in cities:
                v = gs(c, sm, scol)
                txt = f(v, 2)
                cells_txt.append('\\textbf{%s}' % txt if fm != 'Oracle-state' and v - best[('s', c)] < 5e-4 else txt)
            out.append(lab + ' & ' + ' & '.join(cells_txt) + ' \\\\')
            if fm == 'Oracle-state':
                out.append('\\midrule')
        return out

    nc = len(dzs) + len(cities)
    lines = ['\\begin{tabular}{l' + 'c' * nc + '}', '\\toprule',
             '& \\multicolumn{%d}{c}{synthetic, proxy separation $\\Delta_Z$} & \\multicolumn{%d}{c}{real-data-calibrated, hourly} \\\\' % (len(dzs), len(cities)),
             '\\cmidrule(lr){2-%d}\\cmidrule(lr){%d-%d}' % (1 + len(dzs), 2 + len(dzs), 1 + nc),
             'Estimator & ' + ' & '.join(f'{d:g}' for d in dzs) + ' & ' + ' & '.join(c[:3] for c in cities) + ' \\\\',
             '\\midrule', '\\multicolumn{%d}{l}{\\emph{ATE: mean absolute bias}} \\\\' % (1 + nc)]
    lines += block(ROWS, 'mean_abs_bias', 'mean_abs_bias')
    lines += ['\\midrule', '\\multicolumn{%d}{l}{\\emph{Regime effects: median $\\|\\hat{\\boldsymbol\\theta}-\\boldsymbol\\theta^*\\|_2$}} \\\\' % (1 + nc)]
    lines += block(COUPLED, 'theta_err_median', 'theta_err')
    lines.append('\\midrule')
    pe = [gf(d, 'OR-DML', 'eps_hat') for d in dzs] + [ss[ss.city == c].eps_hat.iloc[0] for c in cities]
    lines.append('posterior error $\\varepsilon_\\gamma$ & ' + ' & '.join(f(v, 3) if v >= 5e-4 else '$<$0.001' for v in pe) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_main_comparison'] = '\n'.join(lines)

    s = 'reports/synthesis/frontier_designs_summary.csv'
    L.add('FDNRuns', int(fd[fd.method == 'OR-DML'].n.sum()), s, 'replications (datasets) across all cells', '{:,}')
    L.add('FDStd', gf(2.0, 'Standard DML'), s, 'standard DML bias, dz=2', '{:.2f}')
    L.add('FDBlock', gf(2.0, 'Block DML'), s, 'block DML bias, dz=2', '{:.2f}')
    L.add('FDTrueATE', 1.5278, 'src/synthetic_dgp_benchmark.py', 'stationary ATE of the DGP', '{:.2f}')
    for d, nm in [(1.0, 'One'), (2.0, 'Two'), (4.0, 'Four')]:
        L.add('FDOurs' + nm, gf(d, 'OR-DML'), s, f'OR-DML (posterior-adjusted) ATE bias dz={d}')
        L.add('FDHard' + nm, gf(d, 'Hard regime FE'), s, f'hard FE ATE bias dz={d}')
        L.add('FDFeat' + nm, gf(d, 'Posterior-feature DML'), s, f'posterior-feature ATE bias dz={d}')
        L.add('FDW' + nm, gf(d, 'OR-DML, weighted nuisances'), s, f'weighted OR-DML ATE bias dz={d}')
        L.add('FDOursTh' + nm, gf(d, 'OR-DML', 'theta_err_median'), s, f'OR-DML median regime error dz={d}')
        L.add('FDHardTh' + nm, gf(d, 'Hard regime FE', 'theta_err_median'), s, f'hard FE median regime error dz={d}')
        L.add('FDWTh' + nm, gf(d, 'OR-DML, weighted nuisances', 'theta_err_median'), s, f'weighted median regime error dz={d}')
        L.add('FDCovOurs' + nm, 100 * gf(d, 'OR-DML', 'coverage'), s, f'OR-DML SATE coverage dz={d}', '{:.0f}')
        L.add('FDEps' + nm, gf(d, 'OR-DML', 'eps_hat'), s, f'median posterior error dz={d}', '{:.3f}')
    for p00, nm in [(0.70, 'Lo'), (0.97, 'Hi')]:
        for d, dn in [(1.0, 'One'), (2.0, 'Two')]:
            L.add('FDPer' + nm + dn + 'Ours', gf(d, 'OR-DML', p00=p00), s, f'OR-DML bias p00={p00} dz={d}')
            L.add('FDPer' + nm + dn + 'Hard', gf(d, 'Hard regime FE', p00=p00), s, f'hard FE bias p00={p00} dz={d}')
            L.add('FDPer' + nm + dn + 'Eps', gf(d, 'OR-DML', 'eps_hat', p00=p00), s, f'posterior error p00={p00} dz={d}', '{:.3f}')
    L.add('FDPerMidOneOurs', gf(1.0, 'OR-DML'), s, 'OR-DML bias p00=.88 dz=1')
    L.add('FDPerMidOneEps', gf(1.0, 'OR-DML', 'eps_hat'), s, 'posterior error p00=.88 dz=1', '{:.3f}')
    cells_ate = cells_th = 0
    ncell = 0
    for (d, p00), g in fd.groupby(['dz', 'p00']):
        if d < 1.0:
            continue
        ncell += 1
        nono = g[g.method != 'Oracle-state']
        cells_ate += int(nono[nono.method == 'OR-DML'].mean_abs_bias.iloc[0] <= nono.mean_abs_bias.min() + 1e-3)
        co = g[g.method.isin(['Hard regime FE', 'OR-DML, weighted nuisances', 'OR-DML'])]
        cells_th += int(co[co.method == 'OR-DML'].theta_err_median.iloc[0] <= co.theta_err_median.min() + 1e-3)
    L.add('FDNCells', ncell, s, 'frontier cells with dz>=1', '{:d}')
    L.add('FDBestATE', cells_ate, s, 'cells (dz>=1) where OR-DML ATE bias is within 0.001 of the best non-oracle', '{:d}')
    L.add('FDBestTheta', cells_th, s, 'cells (dz>=1) where OR-DML regime error is within 0.001 of the best coupled', '{:d}')
    lines = ['\\begin{tabular}{cclcccccc}', '\\toprule',
             '$\\Delta_Z$ & $p_{00}$ & Estimator & mean $|$bias$|$ & median & RMSE & cover. & $\\|\\hat{\\boldsymbol\\theta}-\\boldsymbol\\theta^*\\|$ & $\\lambda_{\\min}$ \\\\', '\\midrule']
    for (d, p00), g in fd.groupby(['dz', 'p00'], sort=False):
        for i, r in enumerate(g.itertuples()):
            te = f(r.theta_err_median, 3) if r.theta_err_median == r.theta_err_median else '--'
            lm = f(r.lam, 3) if r.lam == r.lam else '--'
            nm = 'OR-DML (posterior-adjusted)' if r.method == 'OR-DML' else r.method
            lines.append(f'{f(d, 1) if i == 0 else ""} & {f(p00, 2) if i == 0 else ""} & {nm} & {r.mean_abs_bias:.3f} & {r.median_abs_bias:.3f} & {r.rmse:.3f} & {100 * r.coverage:.0f}\\% & {te} & {lm} \\\\')
        lines.append('\\midrule')
    lines[-1] = '\\bottomrule'
    lines.append('\\end{tabular}')
    tabs['tab_frontier_designs'] = '\n'.join(lines)
    lines = ['\\begin{tabular}{ccccccccc}', '\\toprule',
             '$p_{00}$ & $\\Delta_Z$ & switches & $\\varepsilon_\\gamma$ & Post.-feature & Hard FE & OR-DML wtd. & \\textbf{OR-DML} & oracle \\\\', '\\midrule']
    for p00 in (0.70, 0.88, 0.97):
        for d in (1.0, 2.0):
            lines.append(f'{p00:.2f} & {d:g} & {gf(d, "OR-DML", "switches", p00):.0f} & {gf(d, "OR-DML", "eps_hat", p00):.3f} & '
                         + ' & '.join(f(gf(d, m, p00=p00), 3) for m in ['Posterior-feature DML', 'Hard regime FE', 'OR-DML, weighted nuisances', 'OR-DML', 'Oracle-state']) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_frontier_c'] = '\n'.join(lines)

    s = 'reports/synthesis/semisynthetic_hourly_summary.csv'
    gs = lambda c, m, col='mean_abs_bias': ss[(ss.city == c) & (ss.method == m)][col].iloc[0]  # noqa: E731
    for c in cities:
        L.add('SS' + c + 'Feat', gs(c, 'Posterior-feature DML'), s, 'posterior-feature DML bias', '{:.2f}')
        L.add('SS' + c + 'Hard', gs(c, 'Hard regime FE DML'), s, 'hard FE bias', '{:.2f}')
        L.add('SS' + c + 'Soft', gs(c, 'Spectral OR-DML (soft, coupled)'), s, 'soft coupled bias', '{:.2f}')
        L.add('SS' + c + 'Std', gs(c, 'Standard DML (random folds)'), s, 'standard DML bias', '{:.2f}')
        L.add('SS' + c + 'Eps', gs(c, 'Posterior-feature DML', 'eps_hat'), s, 'posterior error', '{:.3f}')
        L.add('SS' + c + 'Law', gs(c, 'Posterior-feature DML', 'law_bias'), s, 'bias-law plug-in prediction', '{:.2f}')
        L.add('SS' + c + 'Obs', gs(c, 'Posterior-feature DML', 'mean_bias'), s, 'observed mean bias', '{:.2f}')
        L.add('SS' + c + 'LamP', gs(c, 'Spectral OR-DML (soft, coupled)', 'lam_proxy'), s, 'lambda proxy', '{:.3f}')
        L.add('SS' + c + 'LamO', gs(c, 'Spectral OR-DML (soft, coupled)', 'lam_oracle'), s, 'lambda oracle', '{:.3f}')
        L.add('SS' + c + 'PA', gs(c, 'OR-DML (posterior-adjusted)'), s, 'posterior-adjusted OR-DML bias', '{:.2f}')
        L.add('SS' + c + 'PATh', gs(c, 'OR-DML (posterior-adjusted)', 'theta_err'), s, 'posterior-adjusted OR-DML regime error', '{:.2f}')
        L.add('SS' + c + 'HardTh', gs(c, 'Hard regime FE DML', 'theta_err'), s, 'hard FE regime error', '{:.2f}')
        L.add('SS' + c + 'WTh', gs(c, 'Spectral OR-DML (soft, coupled)', 'theta_err'), s, 'weighted OR-DML regime error', '{:.2f}')
    accs = 1 - ss.eps_hat / 2
    L.add('SSAccMin', 100 * accs.min(), s, 'min expected state accuracy 1-eps/2', '{:.0f}')
    L.add('SSAccMax', 100 * accs.max(), s, 'max expected state accuracy', '{:.0f}')
    rel = []
    for c in cities:
        rel.append(abs(gs(c, 'Posterior-feature DML', 'law_bias') / gs(c, 'Posterior-feature DML', 'mean_bias') - 1))
    L.add('SSLawErrMin', 100 * min(rel), s, 'min |law/obs-1| %', '{:.0f}')
    L.add('SSLawErrMax', 100 * max(rel), s, 'max |law/obs-1| %', '{:.0f}')
    infl = [gs(c, 'Spectral OR-DML (soft, coupled)', 'lam_proxy') / gs(c, 'Spectral OR-DML (soft, coupled)', 'lam_oracle') for c in cities]
    L.add('SSInflMin', min(infl[1:]), s, 'lambda inflation, non-Delhi min', '{:.1f}')
    L.add('SSInflMax', max(infl[1:]), s, 'lambda inflation, non-Delhi max', '{:.1f}')
    L.add('SSInflDelhi', infl[0], s, 'lambda inflation Delhi', '{:.2f}')
    s = 'reports/synthesis/semisynthetic_hourly_calibration.csv'
    L.add('SSNMin', cal.N.min(), s, 'min N', '{:,}'); L.add('SSNMax', cal.N.max(), s, 'max N', '{:,}')
    L.add('SSStayMin', min(cal.stay0.min(), cal.stay1.min()), s, 'min stay prob', '{:.2f}')
    L.add('SSStayMax', max(cal.stay0.max(), cal.stay1.max()), s, 'max stay prob', '{:.2f}')
    # full semi-synthetic appendix table
    lines = ['\\begin{tabular}{llccccc}', '\\toprule',
             'City & Estimator & $|\\mathrm{bias}|$ & RMSE & cover. & $\\|\\hat\\theta-\\theta\\|$ & $\\lambda_{\\min}$ prx/orc \\\\', '\\midrule']
    for c in cities:
        sub = ss[ss.city == c]
        for i, r in enumerate(sub.itertuples()):
            lam = f'{r.lam_proxy:.3f}/{r.lam_oracle:.3f}' if 'OR-DML' in r.method else ''
            te = f(r.theta_err, 2) if r.theta_err == r.theta_err else '--'
            lines.append(f'{c if i == 0 else ""} & {r.method} & {r.mean_abs_bias:.3f} & {r.rmse:.3f} & {100 * r.coverage:.0f}\\% & {te} & {lam} \\\\')
        lines.append('\\midrule' if c != cities[-1] else '\\bottomrule')
    lines.append('\\end{tabular}')
    tabs['tab_semisynthetic_full'] = '\n'.join(lines)

    # legacy 11-method frontier (appendix; reports/or_dml_benchmark_summary.csv)
    s = 'reports/or_dml_benchmark_summary.csv'
    g = lambda d, m, col='Abs_Bias': bm[(bm.Delta_Z == d) & (bm.Method == m)][col].iloc[0]  # noqa: E731
    L.add('BMTrueATE', 1.5278, s, 'true ATE in DGP', '{:.3f}')
    L.add('BMLamStd', g(1.0, 'Standard DML', 'Mean_Lambda_Min'), s, 'residual variance of standard DML', '{:.2f}')
    L.add('BMLamOracle', g(1.0, 'Oracle DML', 'Mean_Lambda_Min'), s, 'oracle lambda_min', '{:.2f}')
    L.add('BMLamSoftLow', g(0.2, 'Spectral OR-DML (Ours)', 'Mean_Lambda_Min'), s, 'proxy lambda at dz=.2', '{:.2f}')
    L.add('BMEpsLow', g(0.2, 'Spectral OR-DML (Ours)', 'Mean_Proxy_Error'), s, 'proxy error at dz=.2', '{:.2f}')
    L.add('BMZTOne', g(1.0, 'HMM(Z, T) OR-DML'), s, 'HMM(Z,T) at dz=1', '{:.2f}')
    # full synthetic frontier table (appendix)
    keep = ['Oracle DML', 'Standard DML', 'Block DML', 'DML + Z Controls (Ridge)', 'DML + Z Controls (GBM)',
            'Regime FE DML (Hard)', 'Unregularized Coupled DML', 'Spectral OR-DML (Ours)', 'Filtered OR-DML (Ours)',
            'Decoupled Soft OR-DML', 'HMM(Z, T) OR-DML']
    lines = ['\\begin{tabular}{llccccc}', '\\toprule',
             '$\\Delta_Z$ & Estimator & mean $|\\mathrm{bias}|$ & median & RMSE & cov.\\ S/P (\\%) & $\\lambda_{\\min}$ \\\\', '\\midrule']
    for d in sorted(bm.Delta_Z.unique()):
        sub = bm[bm.Delta_Z == d].set_index('Method')
        for i, m in enumerate(keep):
            r = sub.loc[m]
            nm = m.replace('(Ours)', '').replace('HMM(Z, T)', 'HMM$(Z,T)$').strip()
            lines.append(f'{f(d, 1) if i == 0 else ""} & {nm} & {r.Abs_Bias:.3f} & {r.Median_Abs_Bias:.3f} & {r.RMSE:.3f} & {r.Coverage_SATE_95_Pct:.0f}/{r.Coverage_PATE_95_Pct:.0f} & {r.Mean_Lambda_Min:.3f} \\\\')
        lines.append('\\midrule' if d != bm.Delta_Z.max() else '\\bottomrule')
    lines.append('\\end{tabular}')
    tabs['tab_frontier_full'] = '\n'.join(lines)

    # Frontier B / C / regularization / scalability / soft-vs-hard / deep explorations
    fb = pd.read_csv(R('frontier_b_size_distortion_summary.csv'))
    s = 'reports/frontier_b_size_distortion_summary.csv'
    L.add('FBSoft', fb.Empirical_Type_I_Error.iloc[0].replace('%', '\\%'), s, 'type I error OR-DML')
    L.add('FBHard', fb.Empirical_Type_I_Error.iloc[1].replace('%', '\\%'), s, 'type I error hard FE')
    fc = pd.read_csv(R('frontier_c_persistence_stress_summary.csv'))
    s = 'reports/frontier_c_persistence_stress_summary.csv'
    L.add('FCSoftLow', fc[(fc.persistence == 0.3) & (fc.method == 'Spectral OR-DML')].Mean_Abs_Bias.iloc[0], s, 'rho=.3', '{:.2f}')
    L.add('FCSoftHigh', fc[(fc.persistence == 0.88) & (fc.method == 'Spectral OR-DML')].Mean_Abs_Bias.iloc[0], s, 'rho=.88', '{:.2f}')
    L.add('FCHardLow', fc[(fc.persistence == 0.3) & (fc.method == 'Hard Regime FE')].Mean_Abs_Bias.iloc[0], s, 'rho=.3', '{:.2f}')
    L.add('FCHardHigh', fc[(fc.persistence == 0.88) & (fc.method == 'Hard Regime FE')].Mean_Abs_Bias.iloc[0], s, 'rho=.88', '{:.2f}')
    L.add('FCSwLow', fc.Mean_Switches.max(), s, 'switches at rho=.3', '{:.0f}')
    L.add('FCSwHigh', fc.Mean_Switches.min(), s, 'switches at rho=.88', '{:.0f}')
    lines = ['\\begin{tabular}{lccc}', '\\toprule', 'persistence & switches & hard FE $|\\mathrm{bias}|$ & soft OR-DML $|\\mathrm{bias}|$ \\\\', '\\midrule']
    for p in sorted(fc.persistence.unique()):
        h = fc[(fc.persistence == p) & (fc.method == 'Hard Regime FE')].iloc[0]
        o = fc[(fc.persistence == p) & (fc.method == 'Spectral OR-DML')].iloc[0]
        lines.append(f'{p:g} & {h.Mean_Switches:.0f} & {h.Mean_Abs_Bias:.3f} & {o.Mean_Abs_Bias:.3f} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_frontier_c_legacy'] = '\n'.join(lines)
    rg = pd.read_csv(R('or_dml_regularization_frontier.csv'))
    s = 'reports/or_dml_regularization_frontier.csv'
    best_i = rg.MSE.idxmin()
    L.add('RegLamBest', rg.Lambda[best_i], s, 'MSE-minimising lambda', '{:g}')
    L.add('RegRatio', rg.MSE.iloc[0] / rg.MSE[best_i], s, 'MSE(0)/MSE(best)', '{:.0f}')
    L.add('RegCovBest', rg.Coverage_95_Pct[best_i], s, 'coverage at best lambda', '{:.0f}')
    L.add('RegCovZero', rg.Coverage_95_Pct.iloc[0], s, 'coverage at lambda=0', '{:.0f}')
    lines = ['\\begin{tabular}{lcccc}', '\\toprule', '$\\lambda$ & $|\\mathrm{bias}|$ & variance & MSE & coverage (\\%) \\\\', '\\midrule']
    for r in rg.itertuples():
        lines.append(f'{r.Lambda:g} & {r.Abs_Bias:.4f} & {r.Variance:.4f} & {r.MSE:.4f} & {r.Coverage_95_Pct:.0f} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_regularization'] = '\n'.join(lines)
    ms = pd.read_csv(R('multiregime_scalability_summary.csv'))
    lines = ['\\begin{tabular}{lccccc}', '\\toprule', '$K$ & ATE bias & ATE SE & $\\|\\hat\\theta-\\theta\\|_2$ & $\\lambda_{\\min}$ & $\\kappa$ \\\\', '\\midrule']
    for r in ms.itertuples():
        lines.append(f'{r.K} & {r.ATE_Bias:.3f} & {r.ATE_SE:.3f} & {r.L2_Error:.3f} & {r.Lambda_Min:.3f} & {r.Kappa_J:.2f} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_scalability'] = '\n'.join(lines)
    sv = pd.read_csv(R('synthesis', 'soft_vs_hard_continuous_mixture_summary.csv')).iloc[0]
    s = 'reports/synthesis/soft_vs_hard_continuous_mixture_summary.csv'
    L.add('SVHSoft', sv.mean_abs_bias_soft, s, 'soft', '{:.2f}'); L.add('SVHHard', sv.mean_abs_bias_hard, s, 'hard', '{:.2f}')
    L.add('SVHStd', sv.mean_abs_bias_std, s, 'standard', '{:.2f}')
    L.add('SVHWin', 100 * sv.frac_soft_better, s, '% soft better', '{:.0f}')
    L.add('SVHPA', sv.mean_abs_bias_pa, s, 'posterior-adjusted OR-DML', '{:.2f}')
    L.add('SVHPAWin', 100 * sv.frac_pa_better_than_hard, s, '% posterior-adjusted better than hard', '{:.0f}')
    e4 = pd.read_csv(R('deep_eval_exploration4_task_conditioning_summary.csv'))
    s = 'reports/deep_eval_exploration4_task_conditioning_summary.csv'
    L.add('DEErrLo', e4.Mean_Causal_L2_Error.iloc[0], s, 'error at smallest dT', '{:.2f}')
    L.add('DEErrHi', e4.Mean_Causal_L2_Error.iloc[-1], s, 'error at largest dT', '{:.2f}')
    L.add('DELamLo', e4.Mean_Lambda_Min.min(), s, 'min lambda', '{:.2f}'); L.add('DELamHi', e4.Mean_Lambda_Min.max(), s, 'max lambda', '{:.2f}')
    L.add('DEEps', e4.Mean_Proxy_Error.mean(), s, 'mean proxy error', '{:.3f}')
    L.add('DETLo', e4.delta_t.iloc[0], s, 'smallest dT', '{:g}'); L.add('DETHi', e4.delta_t.iloc[-1], s, 'largest dT', '{:g}')

    # ---------------- posterior-adjusted design: orthogonality and coupled residual-state law ---------------
    cl = pd.read_csv(R('synthesis', 'coupled_law_check.csv'))
    s = 'reports/synthesis/coupled_law_check.csv'
    L.add('CLMaxDev', cl.max_abs_dev.max(), s, 'max |estimate - law| over configurations (N=1e6)', '{:.3f}')
    L.add('CLNConf', len(cl), s, 'configurations', '{:d}')
    L.add('CLZeroShift', cl[cl.a == 0].bias_norm.iloc[0], s, 'bias norm with zero treatment shift', '{:.3f}')
    hump = cl[(cl.b == 3.0) & (cl.dtheta == 1.0) & (cl.sigma == 1.0) & (cl.beta_shape == 0.6)].sort_values('a')
    L.add('CLLamLo', hump.lam_min_J.iloc[0], s, 'lambda_min(J) at a=0', '{:.2f}')
    L.add('CLLamHi', hump.lam_min_J.iloc[-1], s, 'lambda_min(J) at a=8', '{:.2f}')
    L.add('CLLamOracle', hump.lam_min_oracle.iloc[0], s, 'oracle lambda_min', '{:.2f}')
    L.add('CLAPeak', hump.loc[hump.bias_norm.idxmax(), 'a'], s, 'treatment shift with largest bias', '{:g}')
    oc = pd.read_csv(R('synthesis', 'orthogonality_check.csv')).set_index('design')
    s = 'reports/synthesis/orthogonality_check.csv'
    L.add('OrthPA', 100 * oc.loc['posterior-adjusted', 'relative_to_jacobian'], s, 'score derivative / Jacobian norm, posterior-adjusted (%)', '{:.1f}')
    L.add('OrthW', 100 * oc.loc['posterior-weighted', 'relative_to_jacobian'], s, 'score derivative / Jacobian norm, posterior-weighted (%)', '{:.0f}')
    lines = ['\\begin{tabular}{rrrrcccc}', '\\toprule', '$a$ & $\\Delta_g$ & $\\Delta\\theta$ & $\\sigma$ & estimate & law & $|$dev.$|$ & $\\lambda_{\\min}(\\bJ)$ \\\\', '\\midrule']
    for r in cl.itertuples():
        lines.append(f'{r.a:g} & {r.b:g} & {r.dtheta:g} & {r.sigma:g} & ({r.est_0:.3f}, {r.est_1:.3f}) & ({r.law_0:.3f}, {r.law_1:.3f}) & {r.max_abs_dev:.4f} & {r.lam_min_J:.3f} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_coupled_law'] = '\n'.join(lines)

    # ---------------- representation zoo ---------------------------------------------------------------------
    ci = pd.read_csv(R('representation_zoo_calibration_intervention.csv')).set_index('Architecture')
    s = 'reports/representation_zoo_calibration_intervention.csv'
    L.add('ZooEceGRU', ci.loc['Neural GRU Encoder', 'ECE_Reduction_Pct'].replace('%', '\\%'), s, 'ECE reduction GRU')
    L.add('ZooEceTr', ci.loc['Causal Transformer Encoder', 'ECE_Reduction_Pct'].replace('%', '\\%'), s, 'ECE reduction Transformer')
    L.add('ZooDaucGRU', ci.loc['Neural GRU Encoder', 'Delta_ROC_AUC'], s, 'AUC change GRU', '{}')
    L.add('ZooDaucTr', ci.loc['Causal Transformer Encoder', 'Delta_ROC_AUC'], s, 'AUC change Transformer', '{}')
    lw = pd.read_csv(R('representation_zoo_lowo_evaluation.csv')).set_index('Features')
    s = 'reports/representation_zoo_lowo_evaluation.csv'
    L.add('LowoFOne', lw.loc['F1', 'LOWO_R2'], s, 'LOWO R2 F1 only'); L.add('LowoFNll', lw.loc['F1+NLL', 'LOWO_R2'], s, 'LOWO R2 F1+NLL')
    au = pd.read_csv(R('representation_zoo_reliability_auc.csv')).set_index('Architecture')
    s = 'reports/representation_zoo_reliability_auc.csv'
    L.add('ZooAucHMM', au.loc['Gaussian HMM (Causal Filter)', 'Reliability_ROC_AUC_D'], s, 'AUC of D_t, HMM', '{:.3f}')
    bench = pd.read_csv(R('latent_regime_bench_models.csv'))
    if 'Baseline_H_AUC' in bench.columns:
        L.add('ZooAucHMMH', bench.iloc[0]['Baseline_H_AUC'], 'reports/latent_regime_bench_models.csv', 'AUC entropy', '{:.3f}')
    lines = ['\\begin{tabular}{lcccccc}', '\\toprule', 'Encoder & $T^\\star$ & ECE raw$\\to$cal. & NLL raw$\\to$cal. & AUC$(\\mathcal D_t)$ raw$\\to$cal. \\\\', '\\midrule']
    for a, r in ci.iterrows():
        lines.append(f'{a} & {r.Optimal_Temperature.split()[0]} & {r.Raw_ECE.split()[0]}$\\to${r.Calibrated_ECE.split()[0]} & {r.Raw_NLL:.3f}$\\to${r.Calibrated_NLL:.3f} & {r.Raw_ROC_AUC_D.split()[0]}$\\to${r.Calibrated_ROC_AUC_D.split()[0]} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_zoo_calibration'] = lines[0].replace('lcccccc', 'lcccc') + '\n' + '\n'.join(lines[1:])
    lines = ['\\begin{tabular}{lcccc}', '\\toprule', 'LOWO predictors & RMSE & $R^2$ & Spearman $\\rho$ & $p$ \\\\', '\\midrule']
    for fe, r in lw.iterrows():
        lines.append(f'{fe.replace("F1", "$F_1$")} & {r.LOWO_RMSE:.4f} & {r.LOWO_R2:.3f} & {r.LOWO_Spearman_rho:.3f} & {r.Spearman_pval:.1e} \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_lowo'] = '\n'.join(lines)

    # ---------------- bias law (v2-bias-law lineage) ---------------------------------------------------------
    bl = json.load(open(R('bias_law', 'summary_numbers.json')))
    s = 'reports/bias_law/summary_numbers.json'
    L.add('BLCorr', bl['e1_corr_law_hat'], s, 'corr law(v_hat) vs bias'); L.add('BLRmse', bl['e1_rmse_law_hat'], s, 'RMSE')
    L.add('BLMedRel', 100 * bl['e1_medrel_law_hat'], s, 'median relative error %', '{:.1f}')
    L.add('BLMedRelTrue', 100 * bl['e1_medrel_law_true'], s, 'median rel err with realised v_N', '{:.1f}')
    L.add('BLCells', bl['e1_cells'], s, 'cells', '{:d}')
    L.add('BLAdjBefore', bl['adj_mae_bfac_0.0'], s, 'MAE uncorrected'); L.add('BLAdjAfter', bl['adj_mae_bfac_1.0'], s, 'MAE corrected')
    L.add('BLTabOneErr', bl['e3_max_abs_err_law_true'], s, 'max abs error on Table-1 DGP', '{:.2f}')
    e7 = pd.read_csv(R('bias_law', 'e7_corrected_conditioning.csv'))
    s = 'reports/bias_law/e7_corrected_conditioning.csv'
    xo = e7[e7.nuisance.str.startswith('X_only')]
    xr = e7[e7.nuisance.str.startswith('X+regime')]
    L.add('ESevLamLo', xo.lam_min.min(), s, 'lambda X-only min', '{:.2f}'); L.add('ESevLamHi', xo.lam_min.max(), s, 'lambda X-only max', '{:.1f}')
    L.add('ESevErrPeak', xo.err_l2.max(), s, 'peak error X-only', '{:.1f}')
    L.add('ESevErrEnd', xo.err_l2.iloc[-1], s, 'error at largest dT X-only', '{:.1f}')
    L.add('ESevRegLo', xr.err_l2.min(), s, 'regime nuisance min error', '{:.2f}'); L.add('ESevRegHi', xr.err_l2.max(), s, 'max', '{:.2f}')
    L.add('ESevRegLam', xr.lam_min.mean(), s, 'regime nuisance lambda', '{:.2f}')

    # ---------------- four-city stress test (corrected hourly grid) ------------------------------------------
    co = pd.read_csv(R('synthesis', 'city_ordml_hourly.csv'))
    pl = pd.read_csv(R('synthesis', 'city_placebo_hourly.csv'))
    au2 = pd.read_csv(R('synthesis', 'city_audit_hourly.csv'))
    x23 = pd.read_csv(R('bias_law', 'x23_real_hourly_fix.csv'))
    lines = ['\\begin{tabular}{lrrrccccc}', '\\toprule',
             'City & $N$ & $\\lambda_{\\min}$ & $\\lambda^{\\rm std}_{\\min}$ & $\\hat\\theta_{\\rm ATE}$ (SE) & $\\hat\\theta_1$ (SE) & $\\hat\\theta_2$ (SE) & lead placebo & $b^\\star$ (SD) \\\\',
             '\\midrule']
    for scr in (False, True):
        for c in cities:
            r = co[(co.city == c) & (co.frozen_screen == scr)].sort_values('regime')
            if scr and c == 'Delhi':
                continue
            r1, r2 = r.iloc[0], r.iloc[1]
            p = pl[(pl.city == c) & (pl.frozen_screen == scr) & (pl.horizon_h < 0)]
            pmin = p.p.min()
            hbad = int(p.loc[p.p.idxmin(), 'horizon_h'])
            verdict = f'rejects ($h{{=}}{hbad}$, $p{{=}}{pmin:.3f}$)' if pmin < 0.05 else f'passes ($p_{{\\min}}{{=}}{pmin:.2f}$)'
            xb = x23[(x23.city == c) & (x23.frozen_screen == scr)].iloc[0]
            name = c + (' (screened)' if scr else '')
            lines.append(f'{name} & {int(r1.N):,} & {r1.lambda_min:.3g} & {r1.lambda_min_std:.2f} & {r1.ate:.3f} ({r1.ate_se:.3f}) & '
                         f'{r1.theta:.3f} ({r1.se:.3f}) & {r2.theta:.3f} ({r2.se:.3f}) & {verdict} & {xb.b_star_sd:.1f} \\\\')
        if not scr:
            lines.append('\\midrule')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_cities'] = '\n'.join(lines)
    s = 'reports/synthesis/city_ordml_hourly.csv'
    gc = lambda c, col, scr=False, reg=1: co[(co.city == c) & (co.frozen_screen == scr) & (co.regime == reg)][col].iloc[0]  # noqa: E731
    L.add('CityDelhiATE', gc('Delhi', 'ate'), s, 'Delhi ATE'); L.add('CityDelhiATESE', gc('Delhi', 'ate_se'), s, 'Delhi ATE SE')
    L.add('CityDelhiATEW', gc('Delhi', 'ate_weighted'), s, 'Delhi ATE, weighted-nuisance OR-DML')
    L.add('CityMaxATEDiff', float((co.ate - co.ate_weighted).abs()[co.city != 'Kolkata'].max()), s, 'max |ATE posterior-adjusted - weighted| outside Kolkata', '{:.2f}')
    L.add('CityDelhiRone', gc('Delhi', 'theta'), s, 'Delhi regime 1'); L.add('CityDelhiRtwo', gc('Delhi', 'theta', reg=2), s, 'Delhi regime 2')
    L.add('CityLamMax', co.lambda_min.max(), s, 'max raw lambda', '{:.1f}'); L.add('CityLamMin', co.lambda_min.min(), s, 'min raw lambda', '{:.4f}')
    L.add('CityLamStdMin', co.lambda_min_std.min(), s, 'min std lambda', '{:.2f}'); L.add('CityLamStdMax', co.lambda_min_std.max(), s, 'max std lambda', '{:.2f}')
    L.add('CityKolkataScrATE', gc('Kolkata', 'ate', True), s, 'Kolkata screened ATE', '{:.2f}')
    L.add('CityMumbaiATE', gc('Mumbai', 'ate'), s, 'Mumbai ATE', '{:.2f}'); L.add('CityMumbaiScrATE', gc('Mumbai', 'ate', True), s, 'Mumbai screened ATE', '{:.2f}')
    L.add('CityMumbaiN', gc('Mumbai', 'N'), s, 'Mumbai N', '{:,}'); L.add('CityMumbaiScrN', gc('Mumbai', 'N', True), s, 'Mumbai screened N', '{:,}')
    s = 'reports/synthesis/city_placebo_hourly.csv'
    dp = pl[(pl.city == 'Delhi') & (~pl.frozen_screen)].set_index('horizon_h')
    L.add('PlDelhiLead', dp.loc[-1, 'ate'], s, 'Delhi lead -1 effect'); L.add('PlDelhiLeadP', dp.loc[-1, 'p'], s, 'p', '{:.3f}')
    L.add('PlDelhiPeak', dp.loc[[1, 3, 6, 12, 24], 'ate'].max(), s, 'Delhi max dynamic effect', '{:.2f}')
    L.add('PlDelhiPeakH', int(dp.loc[[1, 3, 6, 12, 24], 'ate'].idxmax()), s, 'horizon of max', '{:d}')
    kp = pl[(pl.city == 'Kolkata') & (pl.frozen_screen) & (pl.horizon_h < 0)]
    L.add('PlKolkataP', kp.p.min(), s, 'Kolkata screened min placebo p', '{:.4f}')
    s = 'reports/synthesis/city_audit_hourly.csv'
    ga = lambda c, col: au2[(au2.city == c) & (~au2.frozen_screen)][col].iloc[0]  # noqa: E731
    L.add('AuMumbaiRun', ga('Mumbai', 'longest_const_no2_h'), s, 'Mumbai longest constant NO2 run (h)', '{:d}')
    L.add('AuKolkataUniq', ga('Kolkata', 'unique_no2'), s, 'Kolkata distinct NO2', '{:d}')
    L.add('AuHourlyMin', 100 * au2.frac_hourly_steps.min(), s, '% consecutive rows 1h apart, min', '{:.0f}')
    s = 'reports/bias_law/x23_real_hourly_fix.csv'
    xd = x23[(x23.city == 'Delhi') & (~x23.frozen_screen)].iloc[0]
    L.add('BstarDelhi', xd.b_star_sd, s, 'Delhi robustness value (SD)', '{:.0f}')
    L.add('BstarDelhiLo', xd.b_star_sd_lo, s, 'lo', '{:.0f}'); L.add('BstarDelhiHi', xd.b_star_sd_hi, s, 'hi', '{:.0f}')
    L.add('PooledDelhi', xd.theta, s, 'posterior-feature pooled Delhi', '{:.2f}')
    L.add('PooledDelhiLo', xd.theta_lo, s, 'lo', '{:.2f}'); L.add('PooledDelhiHi', xd.theta_hi, s, 'hi', '{:.2f}')
    leg = pd.read_csv(R('bias_law', 'e5_real_city_sensitivity.csv'))
    L.add('LegacyDelhi', leg[(leg.city == 'Delhi') & (~leg.frozen_screen)].theta.iloc[0], 'reports/bias_law/e5_real_city_sensitivity.csv', 'legacy 2-h grid Delhi', '{:.2f}')
    lines = ['\\begin{tabular}{llrrrrrrrrr}', '\\toprule', 'City & screen & ' + ' & '.join(f'$h{{=}}{h}$' for h in [-6, -3, -1, 0, 1, 3, 6, 12, 24]) + ' \\\\', '\\midrule']
    for scr in (False, True):
        for c in cities:
            p = pl[(pl.city == c) & (pl.frozen_screen == scr)].set_index('horizon_h')
            cellsx = []
            for h in [-6, -3, -1, 0, 1, 3, 6, 12, 24]:
                v, pv = p.loc[h, 'ate'], p.loc[h, 'p']
                star = '$^{*}$' if pv < 0.05 else ''
                cellsx.append(f'{v:.2f}{star}')
            lines.append(f'{c} & {"yes" if scr else "no"} & ' + ' & '.join(cellsx) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_placebo'] = '\n'.join(lines)
    hac = pd.read_csv(R('bias_law', 'e6_hac_lag_sensitivity.csv'))
    lines = ['\\begin{tabular}{lc' + 'c' * 4 + '}', '\\toprule', 'City & regime & ' + ' & '.join(f'lag {l}' for l in [12, 24, 72, 168]) + ' \\\\', '\\midrule']
    for c in cities:
        for k in (1, 2):
            sub = hac[(hac.city == c) & (hac.regime == k)].set_index('lag')
            lines.append(f'{c if k == 1 else ""} & {k} & ' + ' & '.join(f'{sub.loc[l, "theta"]:.3f} ({sub.loc[l, "se"]:.3f}; $p{{=}}{sub.loc[l, "p"]:.3f}$)' for l in [12, 24, 72, 168]) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    tabs['tab_hac'] = '\n'.join(lines)

    with open(os.path.join(outdir, 'numbers.tex'), 'w') as fh:
        fh.write(L.tex())
    pd.DataFrame(L.rows).to_csv(os.path.join(outdir, 'claims.csv'), index=False)
    for k, v in tabs.items():
        with open(os.path.join(outdir, k + '.tex'), 'w') as fh:
            fh.write('% AUTO-GENERATED by src/synthesis/make_tables_numbers.py\n' + v + '\n')
    print(f'wrote {len(L.rows)} macros and {len(tabs)} tables to {outdir}')


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(ROOT, 'paper', 'generated'))
    main(ap.parse_args().out)
