"""Write paper/references.tex with exactly the entries of references_all.tex cited in main/appendix/checklist."""
import os, re
H = os.path.dirname(os.path.abspath(__file__))
txt = ''.join(open(os.path.join(H, f)).read() for f in ('main.tex', 'appendix.tex', 'checklist.tex'))
cited = set()
for m in re.finditer(r'\\cite[pt]?\*?(?:\[[^\]]*\])*\{([^}]*)\}', txt):
    cited |= {k.strip() for k in m.group(1).split(',')}
pool = open(os.path.join(H, 'references_all.tex')).read()
items = {re.search(r'\\bibitem\[[^\]]*\]\{([^}]*)\}', p).group(1): p.strip()
         for p in re.split(r'(?=\\bibitem\[)', pool) if p.strip().startswith('\\bibitem')}
missing = sorted(cited - set(items))
if missing:
    raise SystemExit(f'cited but not in references_all.tex: {missing}')
keys = sorted(cited, key=lambda k: re.sub(r'[^a-z]', '', items[k].split(']')[0].lower()))
open(os.path.join(H, 'references.tex'), 'w').write('% AUTO-GENERATED by paper/prune_bib.py\n' + '\n\n'.join(items[k] for k in keys) + '\n')
print(f'{len(keys)} cited references written; {len(items) - len(keys)} uncited entries omitted')
